version: '3.8'
services:
  db:
    image: postgres:15
    container_name: db_tutor_senas
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tutor_senas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tutor_senas_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: backend_tutor_senas
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Sobrescribe el 'localhost' del application.properties por el nombre del contenedor 'db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tutor_senas_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

volumes:
  postgres_data: