"""Static alphabet catalog — single source of truth for letter evaluation rules."""

from __future__ import annotations

ALPHABET_DATA: list[dict] = [
    {"letter": "A", "name": "A", "description": "Cierra el puño y coloca el pulgar al lado del índice.", "fingerPattern": {"thumb": True, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "easy"},
    {"letter": "B", "name": "B", "description": "Extiende los cuatro dedos juntos hacia arriba. Pulgar cruzado.", "fingerPattern": {"thumb": False, "index": True, "middle": True, "ring": True, "pinky": True}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "easy"},
    {"letter": "C", "name": "C", "description": "Curva todos los dedos formando una C.", "fingerPattern": {"thumb": True, "index": True, "middle": True, "ring": True, "pinky": True}, "distanceChecks": [{"from": 4, "to": 8, "maxDistance": 0.25, "label": "acerca el pulgar al índice"}], "holdMs": 700, "thresholdSuccess": 0.72, "difficulty": "medium"},
    {"letter": "D", "name": "D", "description": "Extiende el índice. Los demás tocan el pulgar.", "fingerPattern": {"thumb": None, "index": True, "middle": False, "ring": False, "pinky": False}, "distanceChecks": [{"from": 4, "to": 12, "maxDistance": 0.1, "label": "toca el pulgar con el medio"}], "holdMs": 700, "thresholdSuccess": 0.75, "difficulty": "medium"},
    {"letter": "E", "name": "E", "description": "Curva todos los dedos hacia la palma.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "easy"},
    {"letter": "F", "name": "F", "description": "Une pulgar e índice en círculo. Extiende los otros tres.", "fingerPattern": {"thumb": None, "index": None, "middle": True, "ring": True, "pinky": True}, "distanceChecks": [{"from": 4, "to": 8, "maxDistance": 0.08, "label": "une pulgar con índice"}], "holdMs": 700, "thresholdSuccess": 0.72, "difficulty": "medium"},
    {"letter": "G", "name": "G", "description": "Extiende índice y pulgar hacia el frente.", "fingerPattern": {"thumb": True, "index": True, "middle": False, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "medium"},
    {"letter": "H", "name": "H", "description": "Extiende índice y medio horizontalmente.", "fingerPattern": {"thumb": False, "index": True, "middle": True, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "medium"},
    {"letter": "I", "name": "I", "description": "Extiende solo el meñique.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": True}, "holdMs": 650, "thresholdSuccess": 0.80, "difficulty": "easy"},
    {"letter": "J", "name": "J", "description": "Como la I, traza una J con el meñique.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": True}, "holdMs": 600, "thresholdSuccess": 0.78, "difficulty": "medium"},
    {"letter": "K", "name": "K", "description": "Índice y medio en V, pulgar entre ambos.", "fingerPattern": {"thumb": True, "index": True, "middle": True, "ring": False, "pinky": False}, "holdMs": 700, "thresholdSuccess": 0.72, "difficulty": "hard"},
    {"letter": "L", "name": "L", "description": "Pulgar e índice en forma de L.", "fingerPattern": {"thumb": True, "index": True, "middle": False, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.80, "difficulty": "easy"},
    {"letter": "M", "name": "M", "description": "Pulgar debajo de índice, medio y anular.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 750, "thresholdSuccess": 0.70, "difficulty": "hard"},
    {"letter": "N", "name": "N", "description": "Pulgar debajo de índice y medio.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 750, "thresholdSuccess": 0.70, "difficulty": "hard"},
    {"letter": "Ñ", "name": "Ñ", "description": "Similar a la N con variación regional.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 750, "thresholdSuccess": 0.70, "difficulty": "hard"},
    {"letter": "O", "name": "O", "description": "Todos los dedos forman un círculo con el pulgar.", "fingerPattern": {"thumb": None, "index": None, "middle": None, "ring": None, "pinky": None}, "distanceChecks": [{"from": 4, "to": 8, "maxDistance": 0.09, "label": "une pulgar con índice"}, {"from": 4, "to": 12, "maxDistance": 0.12, "label": "acerca el medio al pulgar"}], "holdMs": 700, "thresholdSuccess": 0.70, "difficulty": "medium"},
    {"letter": "P", "name": "P", "description": "Como K pero apuntando hacia abajo.", "fingerPattern": {"thumb": True, "index": True, "middle": True, "ring": False, "pinky": False}, "holdMs": 700, "thresholdSuccess": 0.72, "difficulty": "hard"},
    {"letter": "Q", "name": "Q", "description": "Pulgar e índice hacia abajo.", "fingerPattern": {"thumb": True, "index": True, "middle": False, "ring": False, "pinky": False}, "holdMs": 700, "thresholdSuccess": 0.72, "difficulty": "medium"},
    {"letter": "R", "name": "R", "description": "Cruza el medio sobre el índice.", "fingerPattern": {"thumb": False, "index": True, "middle": True, "ring": False, "pinky": False}, "distanceChecks": [{"from": 8, "to": 12, "maxDistance": 0.06, "label": "cruza el medio sobre el índice"}], "holdMs": 750, "thresholdSuccess": 0.68, "difficulty": "hard"},
    {"letter": "S", "name": "S", "description": "Puño cerrado, pulgar sobre los dedos.", "fingerPattern": {"thumb": False, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "easy"},
    {"letter": "T", "name": "T", "description": "Pulgar entre índice y medio, puño cerrado.", "fingerPattern": {"thumb": None, "index": False, "middle": False, "ring": False, "pinky": False}, "holdMs": 700, "thresholdSuccess": 0.72, "difficulty": "medium"},
    {"letter": "U", "name": "U", "description": "Índice y medio juntos hacia arriba.", "fingerPattern": {"thumb": False, "index": True, "middle": True, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.80, "difficulty": "easy"},
    {"letter": "V", "name": "V", "description": "Índice y medio separados en V.", "fingerPattern": {"thumb": False, "index": True, "middle": True, "ring": False, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.80, "difficulty": "easy"},
    {"letter": "W", "name": "W", "description": "Índice, medio y anular separados.", "fingerPattern": {"thumb": False, "index": True, "middle": True, "ring": True, "pinky": False}, "holdMs": 650, "thresholdSuccess": 0.78, "difficulty": "easy"},
    {"letter": "X", "name": "X", "description": "Índice en forma de gancho.", "fingerPattern": {"thumb": False, "index": None, "middle": False, "ring": False, "pinky": False}, "holdMs": 700, "thresholdSuccess": 0.70, "difficulty": "medium"},
    {"letter": "Y", "name": "Y", "description": "Pulgar y meñique extendidos.", "fingerPattern": {"thumb": True, "index": False, "middle": False, "ring": False, "pinky": True}, "holdMs": 650, "thresholdSuccess": 0.80, "difficulty": "easy"},
    {"letter": "Z", "name": "Z", "description": "Índice extendido, traza una Z.", "fingerPattern": {"thumb": False, "index": True, "middle": False, "ring": False, "pinky": False}, "holdMs": 600, "thresholdSuccess": 0.78, "difficulty": "medium"},
]

ALPHABET_MAP: dict[str, dict] = {d["letter"]: d for d in ALPHABET_DATA}
TOTAL_LETTERS = len(ALPHABET_DATA)
