spring.application.name=TutorIAInteraccion
server.port=8888

# Configuraci�n de H2 en memoria
spring.datasource.url=jdbc:h2:mem:tutor_senas_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuraci�n de Hibernate para crear las tablas
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilitar la consola web de H2 (�S�per �til!)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=${JWT_SECRET:RmxhQnVnY2FkQWJjREVGMTIzNDU2Nzg5MGFiY2RlRkdISUpLTE1O}
app.jwt.expiration-ms=86400000
